apiVersion: v1
kind: PersistentVolume
metadata:
  name: cam-terraform-pv
  labels:
    type: cam-terraform
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/icp/nfs/cam/CAM_terraform
    server: 10.63.215.139
