apiVersion: v1
kind: PersistentVolume
metadata:
  name: cam-logs-pv
  labels:
    type: cam-logs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/icp/nfs/cam/CAM_logs
    server: 10.63.215.139
